flask_api/app/routes/airport.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required
from ..services.airport_data import get_airports, get_airports_df
from ..services.flight_data import get_flight_data, process_flight_data
from ..services.plot_service import create_plot
from config import Config

airport_blueprint = Blueprint('airport', __name__, template_folder='../../templates', static_folder='../static')

@airport_blueprint.route('/airport', methods=['GET', 'POST'])
@login_required
def airport():
    """
    Route pour sélectionner les aéroports de départ et d'arrivée et afficher le graphique des vols correspondants.
    
    Returns:
        str: Le rendu de la page avec le formulaire de sélection des aéroports et le graphique.
    """
    airports_ls = get_airports()
    airports_df = get_airports_df(Config.FILTRED_AIRPORT_LIST, Config.ALL_AIRPORTS)
    graphJSON = None
    error_message = None

    # Utilisation de valeurs par défaut
    departure_airport_code = "FRA"
    arrival_airport_code = "CDG"

    if request.method == 'POST':
        departure_airport_code = request.form.get('departureAirport')
        arrival_airport_code = request.form.get('arrivalAirport')

        if departure_airport_code and arrival_airport_code:
            # Récupérer les données de vol et les filtrer par les aéroports sélectionnés
            flights, airports = get_flight_data(departure_airport_code, arrival_airport_code)
            flight_df = process_flight_data(flights, airports)

            if not flight_df.empty:
                fig = create_plot(flight_df, airports_df)
                graphJSON = fig.to_json()
            else:
                graphJSON = {}
        else:
            error_message = "Aéroport non trouvé. Veuillez sélectionner des aéroports valides."

        return jsonify({
            'graphJSON': graphJSON,
            'departureAirportCode': departure_airport_code,
            'arrivalAirportCode': arrival_airport_code
        })
    else:
        # Pour le rendu initial de la page
        flights, air = get_flight_data(departure_airport_code, arrival_airport_code)
        flight_df = process_flight_data(flights, air)
        fig = create_plot(flight_df, airports_df)
        graphJSON = fig.to_json()

    return render_template('airport.html', airports=airports_ls, graphJSON=graphJSON, error_message=error_message)

flask_api/app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, login_required
from ..models import User

auth_blueprint = Blueprint('auth', __name__, template_folder='../../templates', static_folder='../static')

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if username == 'admin' and password == 'password':
            user = User(username)
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            return render_template('login.html', error='Invalid credentials')

    return render_template('login.html')

@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

flask_api/app/routes/statistics.py
# app/routes/statistics.py

from flask import Blueprint, render_template
from flask_login import login_required
from ..services.airport_data import get_airports_df
from ..services.flight_data import get_flight_data, process_flight_data
from config import Config
import pandas as pd

# Créez un nouveau blueprint pour les statistiques
statistics_blueprint = Blueprint('statistics', __name__, template_folder='../../templates', static_folder='../static')

@statistics_blueprint.route('/statistics', methods=['GET'])
@login_required
def statistics():
    """
    Route pour afficher les statistiques des vols par aéroport de départ.
    
    Returns:
        str: Le rendu de la page des statistiques.
    """
    airports_df = get_airports_df(Config.FILTRED_AIRPORT_LIST, Config.ALL_AIRPORTS)
    statistics_data = []

    # Exemple de logique pour calculer les statistiques
    for airport_code in airports_df['AirportCode']:
        flights, airports = get_flight_data(departure_airport=airport_code, arrival_airport=None)
        flight_df = process_flight_data(flights, airports)

        # Calculer les statistiques
        total_flights = len(flight_df)
        # delayed_flights = flight_df[flight_df['time_status'] == 'Flight Delayed']
        # delayed_percentage = (len(delayed_flights) / total_flights) * 100 if total_flights > 0 else 0
        preferred_destination = flight_df['destination_code'].mode().iloc[0] if not flight_df.empty else 'N/A'
        avg_delay = flight_df[flight_df['time_status'] == 'Flight Delayed']['delay_minutes'].mean() if 'delay_minutes' in flight_df.columns else float('nan')

        # Vérifier si avg_delay est un NaN
        if not pd.isna(avg_delay):
            # Arrondir et convertir en int
            avg_delay = round(avg_delay,1)  # arrondir peut être fait directement sans conversion en int
        else:
            avg_delay = 'N/A'

        statistics_data.append({
            'airport_code': airport_code,
            'total_flights': total_flights,
            # 'delayed_percentage': delayed_percentage,
            'preferred_destination': preferred_destination,
            'avg_delay': avg_delay
        })

    # Rendre le template avec les données de statistiques
    return render_template('statistics.html', statistics_data=statistics_data)

flask_api/app/routes/tester.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required
from ..services.airport_data import get_airports, get_airports_df
from ..services.flight_data import get_flight_data, process_flight_data
from ..services.plot_service import create_plot
from config import Config

tester_blueprint = Blueprint('tester', __name__, template_folder='../../templates', static_folder='../static')

@tester_blueprint.route('/tester', methods=['GET', 'POST'])
@login_required
def tester():
    """
    Route principale de l'application Flask. Affiche la page d'accueil avec le graphique des vols et des aéroports.
    
    Returns:
        str: Le rendu de la page d'accueil.
    """
    graphJSON = None
    TTT = True
    airports_list = get_airports()
    # airports_list = [
    # {
    #     "AirportCode": "FRA",
    #     "Position": {
    #         "Coordinate": {
    #             "Latitude": 50.0331,
    #             "Longitude": 8.5706
    #         }
    #     },
    #     "CityCode": "FRA",
    #     "CountryCode": "DE",
    #     "LocationType": "Airport",
    #     "Names": {
    #         "Name": {
    #             "@LanguageCode": "en",
    #             "$": "Frankfurt/Main International"
    #         }
    #     },
    #     "UtcOffset": "2.0",
    #     "TimeZoneId": "Europe/Berlin"
    # },
    # {
    #     "AirportCode": "CDG",
    #     "Position": {
    #         "Coordinate": {
    #             "Latitude": 49.0097,
    #             "Longitude": 2.5478
    #         }
    #     },
    #     "CityCode": "PAR",
    #     "CountryCode": "FR",
    #     "LocationType": "Airport",
    #     "Names": {
    #         "Name": {
    #             "@LanguageCode": "en",
    #             "$": "Paris - Charles De Gaulle"
    #         }
    #     },
    #     "UtcOffset": "2.0",
    #     "TimeZoneId": "Europe/Paris"
    # },
    # {
    #     "AirportCode": "JFK",
    #     "Position": {
    #         "Coordinate": {
    #             "Latitude": 40.6397,
    #             "Longitude": -73.7789
    #         }
    #     },
    #     "CityCode": "NYC",
    #     "CountryCode": "US",
    #     "LocationType": "Airport",
    #     "Names": {
    #         "Name": {
    #             "@LanguageCode": "en",
    #             "$": "New York - JFK International, NY"
    #         }
    #     },
    #     "UtcOffset": "-4.0",
    #     "TimeZoneId": "America/New_York"
    # }]
    departure_airport_code = "FRA"
    arrival_airport_code = "CDG"
    flights, air = get_flight_data(departure_airport_code,arrival_airport_code)
    flight_df = process_flight_data(flights, air)
    airports_df = get_airports_df(Config.FILTRED_AIRPORT_LIST, Config.ALL_AIRPORTS)


    fig = create_plot(flight_df, airports_df)
    graphJSON = fig.to_json()
    
    if TTT:
        departure_airport_code = "FRA"
        arrival_airport_code = "JFK"
        # departure_airport_code = request.form.get('departureAirport')
        # arrival_airport_code = request.form.get('arrivalAirport')
        flights, air = get_flight_data(departure_airport_code,arrival_airport_code)
        flight_df = process_flight_data(flights, air)
        airports_df = get_airports_df(Config.FILTRED_AIRPORT_LIST, Config.ALL_AIRPORTS)
        fig = create_plot(flight_df, airports_df)
        graphJSON = fig.to_json()
        # return jsonify({
        #     'graphJSON': graphJSON,
        #     'departureAirportCode': departure_airport_code,
        #     'arrivalAirportCode': arrival_airport_code
        # })
        return render_template('tester.html', airports=airports_list, graphJSON=graphJSON)
    else :

        return render_template('tester.html', airports=airports_list, graphJSON=graphJSON)

flask_api/templates/airport.html
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Flights and Airports - LUFTH_TRACK_DATA</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="header">
        <div class="logo-container">
            <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="Logo" class="logo">
        </div>
        <div class="app-name">LUFTH_TRACK_DATA</div>
        <a href="https://www.lufthansa.com/" style="color: #1B84a0" target="_blank">Site Officiel Lufthansa</a>
        <a href="{{ url_for('auth.logout') }}" style="color: #1B84a0; text-decoration: none; margin-left: 20px;">Logout</a>
    </div>

    <div class="container">
        {% for airport in airports %}
            {% endfor %}
        <form id="airportSelectionForm">
            <label for="departureAirport">Aéroport de Départ:</label>
            <select id="departureAirport" name="departureAirport" required>
                {% for airport in airports %}
                    <option value="{{ airport['AirportCode'] }}">{{ airport['AirportCode'] }} - {{ airport['Names']['Name']['$'] }} - ({{ airport['CountryCode'] }})</option>
                {% endfor %}
            </select>
            
            <label for="arrivalAirport">Aéroport d'Arrivée:</label>
            <select id="arrivalAirport" name="arrivalAirport" required>
                {% for airport in airports %}
                    <option value="{{ airport['AirportCode'] }}">{{ airport['AirportCode'] }} - {{ airport['Names']['Name']['$'] }} - ({{ airport['CountryCode'] }})</option>
                {% endfor %}
            </select>

            <button type="submit">Voir Vols</button>
        </form>

        <form id="indexForm" action="{{ url_for('main.index') }}" method="get">
            <button type="submit">Tous les vols</button>
          </form>
          <form id="statsForm" action="{{ url_for('statistics.statistics') }}" method="get">
            <button type="submit">Statistiques</button>
          </form>


    </div>

    <div id="graph"></div>
    <div id="airportCodes">
        <p>Aéroport de départ: <span id="departureCode"></span></p>
        <p>Aéroport d'arrivée: <span id="arrivalCode"></span></p>
    </div>
    <div id="errorMessage" class="error"></div>
    


    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
            var graphDiv = document.getElementById('graph');

            // Initialiser une carte vide
            var graphJSON = {{ graphJSON | safe }};
            if (graphJSON) {
                Plotly.newPlot(graphDiv, graphJSON.data, graphJSON.layout);
            }
        
            var form = document.getElementById('airportSelectionForm');
            form.addEventListener('submit', function(event) {
                event.preventDefault();
                var formData = new FormData(form);
                fetch('/airport', {
                    method: 'POST',
                    body: formData
                })
                .then(response => response.json())
                .then(data => {
                    if (data.graphJSON) {
                        var graphJSON = JSON.parse(data.graphJSON);
                        Plotly.react(graphDiv, graphJSON.data, graphJSON.layout);
                    } else {
                        console.error('Erreur: Aucune donnée graphique reçue.');
                    }
        
                    // Mettre à jour les codes d'aéroport affichés
                    document.getElementById('departureCode').textContent = data.departureAirportCode;
                    document.getElementById('arrivalCode').textContent = data.arrivalAirportCode;
        
                    // Gérer le message d'erreur
                    if (data.error_message) {
                        document.getElementById('errorMessage').textContent = data.error_message;
                    } else {
                        document.getElementById('errorMessage').textContent = '';
                    }
                })
                .catch(error => console.error('Error:', error));
              });
            });
    </script>
</body>
</html>

flask_api/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Flights and Airports - LUFTH_TRACK_DATA</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="header">
        <div class="logo-container">
            <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="Logo" class = "logo" >
        </div>
      <div class="app-name">LUFTH_TRACK_DATA</div>
      <a href="https://www.lufthansa.com/" style="color: #1B84a0" target="_blank">Site Officiel Lufthansa</a>
      <a href="{{ url_for('auth.logout') }}" style="color: #1B84a0; text-decoration: none; margin-left: 20px;">Logout</a>
    </div>
  
    <div class="radio-buttons">
      <form id="flightTypeForm">
        <input type="radio" id="allFlights" name="flightType" value="all" checked>
        <label for="allFlights">All Flights</label>
        <input type="radio" id="singleFlight" name="flightType" value="single">
        <label for="singleFlight">Single Flights</label>
        <input type="radio" id="connectingFlight" name="flightType" value="connecting">
        <label for="connectingFlight">Connecting Flights</label>
      </form>
       <form action="{{ url_for('airport.airport') }}" method="get">
        <button type="submit">Filtrer par Aéroport</button>
      </form>
    </div>


  
    <div id="graph"></div>
  
    <script type="text/javascript">
      // Script to manage graph display and form interactions
      document.addEventListener('DOMContentLoaded', function() {
        // Get graph container and initial data
        var graphDiv = document.getElementById('graph');
        var graphJSON = {{ graphJSON | safe }};
        Plotly.newPlot(graphDiv, graphJSON.data, graphJSON.layout);
  
        // Add event listener for flight type change
        var form = document.getElementById('flightTypeForm');
        form.addEventListener('change', function() {
          var formData = new FormData(form);
          fetch('/index', {
            method: 'POST',
            body: formData
          })
          .then(response => response.json())
          .then(data => {
            var graphJSON = JSON.parse(data.graphJSON);
            Plotly.react(graphDiv, graphJSON.data, graphJSON.layout);
          })
          .catch(error => console.error('Error:', error));
        });
      });
    </script>
  </body>
  </html>
  

flask_api/templates/index_old.html
<!DOCTYPE html>
<html>
<head>
  <title>Flights and Airports - LUFTH_TRACK_DATA</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <style>
    /* Styles for the page layout and elements */
    body {
      background-color: ;
      font-family: Arial, sans-serif;
      text-align: center;
      margin: 0;
      padding: 0;
    }

    #graph {
      width: 100%;
      height: 80vh;
      margin: 20px auto;
    }

    .radio-buttons {
      margin-top: 20px;
      display: inline-block;
    }

    .radio-buttons form {
      display: inline-block;
    }

    .logo {
      width: 100px; /* Reduce logo size */
      height: 100px; /* Reduce logo size */
      margin-right: 20px;
    }

    .header {
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #002b36;
      padding: 10px;
      color: white;
    }

    .app-name {
      flex: 1;
      font-size: 2em;
      font-weight: bold;
    }

    .header a {
      color: white;
      text-decoration: none;
      font-size: 1.5em;
    }

    .header a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="header">
    <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="LUFTH TRACK DATA Logo">
    <div class="app-name">LUFTH_TRACK_DATA</div>
    <a href="https://www.lufthansa.com/" target="_blank">Site Officiel Lufthansa</a>
    <a href="{{ url_for('logout') }}" style="color: white; text-decoration: none; margin-left: 20px;">Logout</a>
  </div>

  <div class="radio-buttons">
    <form id="flightTypeForm">
      <input type="radio" id="allFlights" name="flightType" value="all" checked>
      <label for="allFlights">All Flights</label>
      <input type="radio" id="singleFlight" name="flightType" value="single">
      <label for="singleFlight">Single Flights</label>
      <input type="radio" id="connectingFlight" name="flightType" value="connecting">
      <label for="connectingFlight">Connecting Flights</label>
    </form>
  </div>

  <div id="graph"></div>

  <script type="text/javascript">
    // Script to manage graph display and form interactions
    document.addEventListener('DOMContentLoaded', function() {
      // Get graph container and initial data
      var graphDiv = document.getElementById('graph');
      var graphJSON = {{ graphJSON | safe }};
      Plotly.newPlot(graphDiv, graphJSON.data, graphJSON.layout);

      // Add event listener for flight type change
      var form = document.getElementById('flightTypeForm');
      form.addEventListener('change', function() {
        var formData = new FormData(form);
        fetch('/', {
          method: 'POST',
          body: formData
        })
        .then(response => response.json())
        .then(data => {
          var graphJSON = JSON.parse(data.graphJSON);
          Plotly.react(graphDiv, graphJSON.data, graphJSON.layout);
        })
        .catch(error => console.error('Error:', error));
      });
    });
  </script>
</body>
</html>

flask_api/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login - LUFTH_TRACK_DATA</title>
    <style>
        body {
            background-color: #002b36;
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
        }

        .login-form {
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            width: 300px;
            background-color: white;
            position: relative;
        }

        .login-form input[type="text"],
        .login-form input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .login-form input[type="submit"] {
            padding: 10px 20px;
            background-color: #0073e6;
            border: none;
            color: white;
            border-radius: 5px;
            cursor: pointer;
        }

        .login-form input[type="submit"]:hover {
            background-color: #005bb5;
        }

        .error {
            color: red;
        }
        .logo {
            width: 250px; /* Ajustez la taille si nécessaire */
            height: 250px;
            margin-bottom: 20px; /* Espacement entre le logo et le formulaire */
          }
    </style>
</head>
<body>
<div class="login-form">
    <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="Logo" class="logo">
    <h2>Login</h2>
    <form method="POST">
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    <input type="submit" value="Login">

    </form>
    {% if error %}
    <p class="error">{{ error }}</p>
    {% endif %}
</div>
</body>
</html>

flask_api/templates/statistics.html
<!-- templates/statistics.html -->

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Statistiques des Vols par Aéroport de Départ - LUFTH_TRACK_DATA</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="header">
        <div class="logo-container">
            <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="Logo" class="logo">
        </div>
        <div class="app-name">LUFTH_TRACK_DATA</div>
        <a href="{{ url_for('auth.logout') }}" style="color: #1B84a0; text-decoration: none; margin-left: 20px;">Logout</a>
    </div>

    <div class="container">
        <h1>Statistiques des Vols par Aéroport de Départ</h1>
        <table border="1">
            <thead>
                <tr>
                    <th>Aéroport de Départ</th>
                    <th>Nombre Total de Vols</th>
                    <th>Pourcentage de Vols Retardés</th>
                    <th>Destination Préférée</th>
                    <th>Retard Moyen (en minutes)</th>
                </tr>
            </thead>
            <tbody>
                {% for stat in statistics_data %}
                <tr>
                    <td>{{ stat.airport_code }}</td>
                    <td>{{ stat.total_flights }}</td>
                    <td>{{ stat.delayed_percentage }}%</td>
                    <td>{{ stat.preferred_destination }}</td>
                    <td>{{ stat.avg_delay }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

flask_api/templates/tester.html
<!DOCTYPE html>
<html>
<head>
  <title>Flights and Airports - LUFTH_TRACK_DATA</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="header">
        <div class="logo-container">
            <img src="{{ url_for('static', filename='images/logo_LUFTH_TRACK_DATA_250x250.png') }}" alt="Logo" class = "logo" >
        </div>
      <div class="app-name">LUFTH_TRACK_DATA</div>
      <a href="https://www.lufthansa.com/" style="color: #1B84a0" target="_blank">Site Officiel Lufthansa</a>
      <a href="{{ url_for('auth.logout') }}" style="color: #1B84a0; text-decoration: none; margin-left: 20px;">Logout</a>
    </div>
  
    <div class="container">
      {% for airport in airports %}
          {% endfor %}
      <form id="airportSelectionForm">
          <label for="departureAirport">Aéroport de Départ:</label>
          <select id="departureAirport" name="departureAirport" required>
              {% for airport in airports %}
                  <option value="{{ airport['AirportCode'] }}">{{ airport['AirportCode'] }} - {{ airport['Names']['Name']['$'] }} - ({{ airport['CountryCode'] if 'CountryCode' in airport else 'Inconnu' }})</option>
              {% endfor %}
          </select>
          
          <label for="arrivalAirport">Aéroport d'Arrivée:</label>
          <select id="arrivalAirport" name="arrivalAirport" required>
              {% for airport in airports %}
                  <option value="{{ airport['AirportCode'] }}">{{ airport['AirportCode'] }} - {{ airport['Names']['Name']['$'] }} - ({{ airport['CountryCode'] if 'CountryCode' in airport else 'Inconnu' }})</option>
              {% endfor %}
          </select>

          <button type="submit">Voir Vols</button>
      </form>

      <form id="indexForm" action="{{ url_for('main.index') }}" method="get">
        <button type="submit">Tous les vols</button>
      </form>
    </div>
  
    <div id="graph"></div>
  
    <script type="text/javascript">
      // Script to manage graph display and form interactions
      document.addEventListener('DOMContentLoaded', function() {
        
        var graphDiv = document.getElementById('graph');
        
         // Initialiser une carte vide
        var graphJSON = {{ graphJSON | safe }};
        Plotly.newPlot(graphDiv, graphJSON.data, graphJSON.layout);
  
        // Add event listener for flight type change
        var form = document.getElementById('airportSelectionForm');
        form.addEventListener('submit', function(event){
          event.preventDefault();
          var formData = new FormData(form);
          fetch('/tester', {
            method: 'POST',
            body: formData
          })
          .then(response => response.json())
          .then(data => {
            var graphJSON = JSON.parse(data.graphJSON);
            Plotly.react(graphDiv, graphJSON.data, graphJSON.layout);
          })
          .catch(error => console.error('Error:', error));
        });
      });
    </script>
  </body>
  </html>
  